import { qs, toast } from '../utils/dom.js';
import { today } from '../utils/date.js';
import { dataService } from '../data/data-service.js';
import { openModal } from '../components/modal.js';

let lastReport = '';

export function generateWeeklyReport() {
  const data = dataService.getData();
  const now = new Date();
  const wk = new Date();
  wk.setDate(wk.getDate() - 7);
  const wkStr = wk.toISOString().split('T')[0];
  const nowStr = today();
  const inRange = (d) => d && d >= wkStr && d <= nowStr;

  const doneTasks = data.tasks.filter((t) => t.status === 'done');
  const progTasks = data.tasks.filter((t) => t.status === 'in-progress');

  const weekPomos = data.pomoRecords.filter((r) => inRange(r.date));
  const pomoByTask = {};
  weekPomos.forEach((r) => {
    const t = data.pomoTasks.find((x) => x.id === r.taskId);
    const name = t ? t.title : '未知任务';
    pomoByTask[name] = (pomoByTask[name] || 0) + 1;
  });

  const readPapers = data.papers.filter((p) => p.status === 'read');
  const deepPapers = data.papers.filter((p) => p.status === 'deep-read');
  const readingPapers = data.papers.filter((p) => p.status === 'reading');

  const weekHabitLogs = data.habitLogs.filter((l) => inRange(l.date));
  const habitCounts = {};
  weekHabitLogs.forEach((l) => {
    const h = data.habits.find((x) => x.id === l.id);
    const name = h ? h.name : '未知';
    habitCounts[name] = (habitCounts[name] || 0) + 1;
  });

  const activeMs = data.milestones.filter((m) => m.status === 'in-progress');

  let r = '# 周报 Weekly Report\n';
  r += '> ' + wkStr + ' ~ ' + nowStr + '\n\n';

  r += '## 1. 任务进展\n';
  if (doneTasks.length) {
    r += '**已完成 (' + doneTasks.length + '):**\n';
    doneTasks.forEach((t) => {
      r += '- [x] ' + t.title + (t.deadline ? ' (DDL: ' + t.deadline + ')' : '') + '\n';
    });
  }
  if (progTasks.length) {
    r += '\n**进行中 (' + progTasks.length + '):**\n';
    progTasks.forEach((t) => {
      r += '- [ ] ' + t.title + (t.deadline ? ' (DDL: ' + t.deadline + ')' : '') + '\n';
    });
  }
  if (!doneTasks.length && !progTasks.length) r += '_暂无任务记录_\n';

  r += '\n## 2. 深度专注\n';
  r += '本周共完成 **' + weekPomos.length + ' 个番茄钟** (' + weekPomos.length * 25 + ' 分钟)\n';
  if (Object.keys(pomoByTask).length) {
    r += '\n| 专注目标 | 番茄数 | 时长 |\n|---------|--------|------|\n';
    Object.entries(pomoByTask)
      .sort((a, b) => b[1] - a[1])
      .forEach(([name, cnt]) => {
        r += '| ' + name + ' | ' + cnt + ' | ' + cnt * 25 + 'min |\n';
      });
  }

  r += '\n## 3. 文献阅读\n';
  r += '- 论文库总计: **' + data.papers.length + ' 篇**\n';
  if (deepPapers.length) {
    r += '- 精读中: ';
    deepPapers.forEach((p) => { r += '_' + p.title + '_ '; });
    r += '\n';
  }
  if (readingPapers.length) {
    r += '- 在读: ';
    readingPapers.forEach((p) => { r += '_' + p.title + '_ '; });
    r += '\n';
  }
  if (readPapers.length) r += '- 已读: ' + readPapers.length + ' 篇\n';

  r += '\n## 4. 习惯打卡\n';
  if (Object.keys(habitCounts).length) {
    Object.entries(habitCounts)
      .sort((a, b) => b[1] - a[1])
      .forEach(([name, cnt]) => { r += '- ' + name + ': **' + cnt + '/7** 天\n'; });
  } else {
    r += '_本周暂无打卡记录_\n';
  }

  if (activeMs.length) {
    r += '\n## 5. 里程碑进度\n';
    activeMs.forEach((m) => {
      const lt = data.tasks.filter((t) => t.milestoneId === m.id);
      const dt = lt.filter((t) => t.status === 'done').length;
      const pct = lt.length ? Math.round((dt / lt.length) * 100) : 0;
      r += '- **' + m.name + '**: ' + pct + '% (' + dt + '/' + lt.length + ' 任务完成)';
      if (m.endDate) r += ' | DDL: ' + m.endDate;
      r += '\n';
    });
  }

  r += '\n---\n_Generated by TaskFlow Pro @ ' + new Date().toLocaleString('zh-CN') + '_\n';

  lastReport = r;
  qs('#reportContent').textContent = r;
  openModal('reportModal');
}

export function copyReport() {
  navigator.clipboard.writeText(lastReport).then(() => toast('已复制到剪贴板!')).catch(() => {
    const ta = document.createElement('textarea');
    ta.value = lastReport;
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    ta.remove();
    toast('已复制到剪贴板!');
  });
}
